[workspace]
authors = ["thuvasooriya <74165167+thuvasooriya@users.noreply.github.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "ros2as"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
# build workspace
build = {cmd = "colcon build --symlink-install", inputs = ["src"]}

# monitor sensors topic
sensors = "bash -c 'source install/setup.sh && ros2 topic echo /zumo/zumo_sensors'"

# visualize with rqt
rqt = "bash -c 'source install/setup.sh && rqt'"

# tutorial
turtlesim = "ros2 run turtlesim turtlesim_node"

# prelab tasks
plab_t2t = "ros2 run cpp_pubsub talker"
plab_t2l = "ros2 run cpp_pubsub listener"
plab_t4 = "ros2 run cpp_pubsub sine_talker"
plab_t5 = "ros2 run cpp_pubsub sine_listener"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-ament-cmake-auto = ">=1.3.12,<2"
compilers = ">=1.11.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
ros-humble-xacro = ">=2.0.13,<3"

[activation]
scripts = ["install/setup.sh"]
[target.win-64.activation]
scripts = ["install/setup.bat"]
