[workspace]
name = "ros2labs"
version = "0.0.13"
authors = ["thuvasooriya <74165167+thuvasooriya@users.noreply.github.com>"]
channels = ["robostack-humble", "conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
# build workspace
build = {cmd = "colcon build --symlink-install", inputs = ["src"]}

# monitor sensors topic
sensors = "bash -c 'source install/setup.sh && ros2 topic echo /zumo/zumo_sensors'"

# visualize with rqt
rqt = "bash -c 'source install/setup.sh && rqt'"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-ament-cmake-auto = ">=1.3.12,<2"
ros-humble-xacro = ">=2.0.13,<3"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
compilers = ">=1.11.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
pyserial = ">=3.5,<4"

[activation]
scripts = ["install/setup.sh"]
[target.win-64.activation]
scripts = ["install/setup.bat"]
