<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="zumo">

	<!-- materials for visualization -->
  <xacro:include filename="$(find zumo_description)/urdf/materials.urdf.xacro" />

	<!-- ##### Properties #####-->

	<!-- General properties -->
	<xacro:property name="M_PI" value="3.1415926535897931" />

	<!-- Base properties -->
	<!-- https://www.pololu.com/file/download/zumo-32u4-main-board-dimension-diagram.pdf?file_id=0J947 -->
	<xacro:property name="chassis_length" value="0.0828" /> 
	<xacro:property name="chassis_width" value="0.066" />      	      	      	      	
	<xacro:property name="chassis_height" value="0.02" />
	<xacro:property name="base_mass" value="0.1" /> <!-- [kg] some arbitrary value -->

	<!-- Wheel properties -->
	<xacro:property name="wheel_radius" value="0.0195" /> <!-- https://www.pololu.com/docs/0J63/all#3.13 -->
	<xacro:property name="wheel_thickness" value="0.014" /> <!-- measured [TODO: check this value] -->
	<xacro:property name="wheel_mass" value="0.01" /> <!-- [kg] some arbitrary valu -->
	
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.02375" /> <!-- measured [TODO: check this value]; using datasheet values (86 - 39)/2 = 0.0235 --> 	
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.042" /> <!-- https://www.pololu.com/docs/0J63/all#3.13 & measured value -->
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.0035" /> <!-- measured [TODO: check this value] -->

	<!-- Crawler boxe properties -->
	<xacro:property name="crawler_box_mass" value="0.01" /> <!-- [kg] some arbitrary value -->


	<!-- ##### macros ##### -->

	<!-- default macros -->
	<xacro:macro name="default_inertial" params="mass *origin">
		<inertial>
			<xacro:insert_block name="origin"/>
			<mass value="${mass}" />
				<inertia ixx="0.01" ixy="0.0" ixz="0.0"
				       iyy="0.01" iyz="0.0"
				       izz="0.01" />
			</inertial>
	</xacro:macro>

	<!-- wheel macro -->
  <xacro:macro name="wheel" params="fb lr parent translateX translateY"> <!--fb : front, back ; lr: left, right -->
    <link name="${fb}_${lr}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" /> 
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" /> 
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
        </geometry>
      </collision>
			<xacro:default_inertial mass="${wheel_mass}">
					<origin xyz="0 0 0" rpy="0 0 0"/>		<!-- TODO: change this according to the real center of gravity if necessary -->
			</xacro:default_inertial>
    </link> 
 
    <joint name="${fb}_${lr}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${fb}_${lr}_wheel"/>
      <origin xyz="${translateX * base_x_origin_to_wheel_origin} ${translateY * base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin}" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>
 
  </xacro:macro>

	<!-- crawler box macro -->
	<xacro:macro name="crawler_box" params="side parent translateY">
		<link name="${side}_crawler_link">
			<xacro:default_inertial mass="${crawler_box_mass}">
					<origin xyz="0 0 0" rpy="0 0 0"/>		<!-- TODO: change this according to the real center of gravity if necessary -->
			</xacro:default_inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
						<box size="${2 * base_x_origin_to_wheel_origin} ${wheel_thickness} ${2 * wheel_radius}"/> 
				</geometry>
				<material name="Black" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
						<box size="${2 * base_x_origin_to_wheel_origin} ${wheel_thickness} ${2 * wheel_radius}"/> 
				</geometry>
			</collision>
		</link>

		  <joint name="${side}_crawler_joint" type="fixed">
		    <parent link="${parent}"/>
		    <child link="${side}_crawler_link"/>
		    <origin xyz="0 ${translateY * base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin}" rpy="0 0 0" /> 
		    <axis xyz="1 0 0" rpy="0 0 0" />
		  </joint>

	</xacro:macro>

	<!-- base macro -->
	<xacro:macro name="zumo_base" params="name">

		<!-- base footprint -->
		<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
		<link name="base_footprint">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</visual>
		</link>

		<!-- base link -->
		<link name="${name}_link">
			<xacro:default_inertial mass="${base_mass}">
					<origin xyz="0 0 0" rpy="0 0 0"/>		<!-- TODO: change this according to the real center of gravity if necessary -->
			</xacro:default_inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
			  		<box size="${chassis_length} ${chassis_width} ${chassis_height}"/> 
				</geometry>
				<material name="Blue" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
			  		<box size="${chassis_length} ${chassis_width} ${chassis_height}"/> 
				</geometry>
			</collision>
		</link>

		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
		  <parent link="base_footprint"/>
		  <child link="base_link" />
		</joint>

		<!-- crawler boxes -->
		<xacro:crawler_box side="left" parent="base_link" translateY="1" />
		<xacro:crawler_box side="right" parent="base_link" translateY="-1" />

		<!-- wheels -->
		<xacro:wheel fb="front" lr="right" parent="base_link" translateX="1" translateY="-1" />
		<xacro:wheel fb="front" lr="left" parent="base_link" translateX="1" translateY="1" />
		<xacro:wheel fb="back" lr="right" parent="base_link" translateX="-1" translateY="-1" />
		<xacro:wheel fb="back" lr="left" parent="base_link" translateX="-1" translateY="1" />

	</xacro:macro>

	<xacro:zumo_base name="base"/>

</robot>
